# Generated by Django 3.1.7 on 2021-03-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210315_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[('ADMIN', 'ADMIN'), ('TEACHER', 'TEACHER'), ('MENTOR', 'MENTOR'), ('STUDENT', 'STUDENT'), ('CLIENT', 'CLIENT')], default='CLIENT', verbose_name='Тип пользователя'),
        ),
    ]
