# Generated by Django 3.1.7 on 2021-03-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210315_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('TEACHER', 'TEACHER'), ('MENTOR', 'MENTOR'), ('STUDENT', 'STUDENT'), ('CLIENT', 'CLIENT')], default='CLIENT', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
