# Generated by Django 3.1.7 on 2021-03-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210315_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone number'),
        ),
    ]
