# Generated by Django 3.1.7 on 2021-03-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Прикрепите файл'),
        ),
    ]
