# Generated by Django 3.1.7 on 2021-03-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_request_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
    ]
