# Generated by Django 3.1.7 on 2021-03-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210315_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingEvent',
        ),
    ]
