# Generated by Django 3.1.7 on 2021-03-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210315_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
